const icons = {
  Home: require('../assets/icons/home.png'),
  World: require('../assets/icons/world.png'),
  User: require('../assets/icons/user.png'),
  PK: require('../assets/icons/pk.png'),
  US: require('../assets/icons/uk.png'),
  Menu: require('../assets/icons/menu.png'),
  TeamWork: require('../assets/icons/tw.png'),
  Notify: require('../assets/icons/notify.png'),
  Assignment: require('../assets/icons/assignment.png'),
  Lecture: require('../assets/icons/lecture.png'),
  Search: require('../assets/icons/search.png'),
  Info: require('../assets/icons/info.png'),
  Study: require('../assets/icons/study.png'),
  Lock: require('../assets/icons/padlock.png'),
  Quran: require('../assets/icons/quran.png'),
  Allah: require('../assets/icons/allah.png'),
  Calendar: require('../assets/icons/calendar.png'),
  Clock: require('../assets/icons/clock.png'),
  Teacher: require('../assets/icons/teacher.png'),
  Share: require('../assets/icons/share.png'),
  Logo: require('../assets/icons/logo.png'),
  Qibla: require('../assets/icons/qibla.png'),
  Pray: require('../assets/icons/praying.png'),
  Manage: require('../assets/icons/manage.png'),
  Parent: require('../assets/icons/parent.png'),
  Std: require('../assets/icons/std.png'),
  StdList: require('../assets/icons/muslim.png'),
  TeacherList: require('../assets/icons/teach.png'),
  Man: require('../assets/icons/man.png'),
  Quotes: require('../assets/icons/quotes.png'),
  Back: require('../assets/icons/back.png'),
  Masjid: require('../assets/icons/masjid.png'),
  MasjidIcon: require('../assets/icons/masjidicon.png'),
  Apps: require('../assets/icons/app.png'),
  MainLogo: require('../assets/icons/mainlogo.png'),
  Logout: require('../assets/icons/logout.png'),
  Cross: require('../assets/icons/cross.png'),
  Alif: require('../assets/icons/alif.png'),
  Madarsa: require('../assets/icons/school.png'),
  Next: require('../assets/icons/next.png'),
  Prev: require('../assets/icons/pre.png'),
  Assign: require('../assets/icons/assign.png'),

  //images
  Student: require('../assets/img/std.jpg'),
  School: require('../assets/img/school.jpg'),
};

export default icons;


